// 易宝产业SD智慧园区/2.27-SR-W9-KJ6NSj-自定义区间日期组件-reporting-react-plugin/src/components/child/index.js
import {
  useRef,
  useState,
  useEffect
} from "react"
import PropTypes from "prop-types"
import { Input } from "antd"

import useDelegator from "../../utils/handlePlatform/UseDelegator.js"
import eventActionDefinitions from "./eventActionDefinitions.js"
import { getThemeStyle } from "../themeColor"

const Child = ({
                 data,
                 onChange,
                 formConfig,
                 component,
                 customConfig,
                 theme,
                 child_id,
                 index
               }) => {
  const state2 = useRef(data)
  const [state, setState] = useState(data)
  const [configuration, setConfiguration] = useState({})
  useEffect(() => {
    setConfiguration(customConfig)
  }, [])

  const triggerEvent = async (eventName, payload) => {
    await window.eventCenter.triggerEventNew({
      objectId: formConfig?.id,
      componentId: component.id,
      type: "report",
      event: eventName,
      payload: { ...payload, childIndex: index }
    })
  }

  const do_EventCenter_message = ({ value }) => {
    alert(value)
  }
  const actionFunDefinitions = {
    do_EventCenter_message
  }

  const Event_Center_getName = () => {
    return `${formConfig?.form_name}-${component.columnStyle.title}`
  }

  // 事件中心注册挂载
  useDelegator(
    component.id,
    { Event_Center_getName, ...actionFunDefinitions },
    eventActionDefinitions,
    formConfig?.id,
    child_id,
    index,
    { eventCenter: window.eventCenter, componentCenter: window.componentCenter }
  )
  return (
    // <Input
    //   style={getThemeStyle(formConfig.theme)}
    //   value={state}
    //   defaultValue={data}
    //   onChange={(e) => {
    //     onChange(e.target.value)
    //     triggerEvent("change", { value: e.target.value })
    //     state2.current = e.target.value
    //     setState(e.target.value)
    //   }}
    //   {...configuration}
    // />
    <></>
  )
}
Child.propTypes = {
  data: PropTypes.string,
  onChange: PropTypes.func
}

export default Child

// 金陵石化炼油厂项目/2.20-SR-W8-bnHGjU-弹窗选择子表二开-reporting-vue-plugin/src/components/Child.vue
<template>
   <el-input v-model="data" @input="inputChange" size="small" />
</template>

<script>
import eventActionDefine from "./msgCompConfig";
export default {
   name: "Add",
   props: {
      customConfig: Object,
   },
   data() {
      return {
         data: this.customConfig.data,
      };
   },
   mounted() {
      let { component, child_id = "", index } = this.customConfig;
      let initId = `${component?.id}__childId__${child_id.substr(0, 10)}`;
      initId = `${initId}__index__${index}`;
      window?.componentCenter?.register(initId, "comp", this, eventActionDefine);
   },
   methods: {
      async inputChange(e) {
         this.data = e;
         let { formConfig, component, child_id = "", index, onChange } = this.customConfig;
         let initId = `${component?.id}__childId__${child_id.substr(0, 10)}`;
         await window.eventCenter.triggerEventNew({
            objectId: formConfig?.id,
            componentId: initId,
            type: "report",
            event: "change",
            payload: {
               value: e,
               childIndex: index,
            },
         });
         onChange(e);
      },
      Event_Center_getName() {
         let { formConfig, component } = this.customConfig;
         return `${formConfig?.form_name}-${component.columnStyle.title}`;
      },
      do_EventCenter_setValue({ value }) {
         this.data = value;
      },
      Event_Center_getName() {
         return this.data;
      },
   },
   destroyed() {
      let { component, child_id = "", index } = this.customConfig;
      let initId = `${component?.id}__childId__${child_id.substr(0, 10)}`;
      initId = `${initId}__index__${index}`;
      window?.componentCenter?.removeInstance(initId);
   },
};
</script>

<style></style>
