// 磐能电力（R）/1.30-SR-W2-qnVhRm-pv组件定制-reporting-vue-plugin/src/App.vue
<template>
  <component :is="componentType" :customConfig="customConfig" />
</template>

<script>
import Set from "./components/Set.vue";
import Add from "./components/Add.vue";
import AddMultiple from "./components/AddMultiple.vue";
import Child from "./components/Child.vue";
import Preview from "./components/Preview.vue";
import Table from "./components/Table.vue";
import DesignConfiguration from "./components/DesignConfiguration.vue";

export default {
  name: "App",
  props: {
    type: String,
    customConfig: Object,
  },
  components: {
    Set,
    Add,
    AddMultiple,
    Child,
    Preview,
    Table,
    DesignConfiguration,
  },
  // created() {
  //   // console.log(this.customConfig, '======')

  // },
  computed: {
    componentType: function () {
      return this.type.slice(0, 1).toUpperCase() + this.type.slice(1);
    },
  },
};
</script>

// 玻纤院-算法模型（R）/2.13-SR-W7-p1pbyV-二开表单组件python代码编辑框-reporting-react-plugin/src/App.js
import React from "react";

import {
  Add,
  Detail,
  DesignConfiguration,
  Design,
  Child,
  List,
  Query,
} from "./components";
import PropTypes from "prop-types";

const renderMap = {
  set: Design,
  add: Add,
  child: Child,
  table: List,
  preview: Detail,
  designConfiguration: DesignConfiguration,
  query: Query,
};
const App = (props) => {
  let Comp = () => <></>;
  if (renderMap[props.type]) Comp = renderMap[props.type];
  return <Comp {...props} />;
};
App.propTypes = {
  type: PropTypes.string,
};

export default App;
